services:
    nginx:
      restart: unless-stopped
      container_name: nginx
      build:
          context: .
          dockerfile: ./Dockerfile
      ports:
          - "81:80"
      volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf:ro